# Generated by Django 5.1 on 2024-08-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_sensordata_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='value',
        ),
    ]
