# Generated by Django 5.1 on 2024-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_sensordata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='value',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
