# Generated by Django 5.1 on 2024-08-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_sensordata_timestamp_alter_sensordata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensor_name',
            field=models.CharField(default='Unknow sensor', max_length=100),
        ),
    ]
